DROP TABLE IF EXISTS files;

PRAGMA encoding = 'UTF-8';

CREATE TABLE files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    userid INTEGER NOT NULL,
    filename TEXT NOT NULL,
    filetype TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    keyfile TEXT NOT NULL,
    macaddr TEXT DEFAULT NULL
);
