DROP TABLE IF EXISTS files;

PRAGMA encoding = 'UTF-8';

CREATE TABLE files (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    uploaded TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    filename TEXT NOT NULL,
    filetype TEXT NOT NULL
);
